
hook.Add( "PopulateToolMenu", "CraftingOptions", function()
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Health", "Table Actions", "", "", function( panel )
		panel:NumSlider( "Max Health", "Craft_Config_MaxHealth", 0, 1000, 0 )
		panel:CheckBox( "Should Explode", "Craft_Config_Should_Explode" )
		panel:CheckBox( "Allow Automation", "Craft_Config_Allow_Automation" )
		panel:NumSlider( "Automation Time", "Craft_Config_Automation_Time", 1, 1800, 0 )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Appearance", "Table Appearance", "", "", function( panel )
		panel:TextEntry( "Table Model", "Craft_Config_Model" )
		panel:TextEntry( "Table Material", "Craft_Config_Material" )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Sounds", "Table Sounds", "", "", function( panel )
		panel:TextEntry( "Item Place Sound", "Craft_Config_Place_Sound" )
		panel:TextEntry( "Craft Sound", "Craft_Config_Craft_Sound" )
		panel:TextEntry( "UI Sound", "Craft_Config_UI_Sound" )
		panel:TextEntry( "Select Sound", "Craft_Config_Select_Sound" )
		panel:TextEntry( "Fail Sound", "Craft_Config_Fail_Sound" )
		panel:TextEntry( "Drop Sound", "Craft_Config_Drop_Sound" )
		panel:TextEntry( "Destroy Sound", "Craft_Config_Destroy_Sound" )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Mining", "Mining Config", "", "", function( panel )
		panel:NumSlider( "Max Rock Health", "Craft_Config_Rock_Health", 0, 1000, 0 )
		panel:NumSlider( "Rock Respawn Time", "Craft_Config_Rock_Respawn", 1, 3600, 0 )
		panel:NumSlider( "Max Tree Health", "Craft_Config_Tree_Health", 0, 1000, 0 )
		panel:NumSlider( "Tree Respawn Time", "Craft_Config_Tree_Respawn", 1, 3600, 0 )
		panel:NumSlider( "Min Mining Spawn", "Craft_Config_Min_Spawn", 1, 25, 0 )
		panel:NumSlider( "Max Mining Spawn", "Craft_Config_Max_Spawn", 1, 25, 0 )
	end )
end )

local function ChangeCvar( name, old, new )
	net.Start( "Craft_ChangeCvar" )
	net.WriteString( name )
	net.WriteString( new )
	net.SendToServer()
end

cvars.AddChangeCallback( "Craft_Config_MaxHealth", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Model", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Material", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Place_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Craft_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_UI_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Select_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Fail_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Drop_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Should_Explode", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Destroy_Sound", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Tree_Health", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Tree_Respawn", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Min_Spawn", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Max_Spawn", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Rock_Health", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Rock_Respawn", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Automation_Time", ChangeCvar )
cvars.AddChangeCallback( "Craft_Config_Allow_Automation", ChangeCvar )
