
hook.Add( "PopulateToolMenu", "CraftingOptions", function()
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Health", "Table Health", "", "", function( panel )
		panel:NumSlider( "Max Health", "Craft_Config_MaxHealth", 0, 1000, 0 )
		panel:CheckBox( "Should Explode", "Craft_Config_Should_Explode" )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Appearance", "Table Appearance", "", "", function( panel )
		panel:TextEntry( "Table Model", "Craft_Config_Model" )
		panel:TextEntry( "Table Material", "Craft_Config_Material" )
		panel:TextEntry( "Table Color", "Craft_Config_Color" )
		panel:TextEntry( "Menu Background Color", "Craft_Config_Menu_Color" )
		panel:TextEntry( "Button Color", "Craft_Config_Button_Color" )
		panel:TextEntry( "Button Text Color", "Craft_Config_Button_Text_Color" )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Sounds", "Table Sounds", "", "", function( panel )
		panel:TextEntry( "Item Place Sound", "Craft_Config_Place_Sound" )
		panel:TextEntry( "Craft Sound", "Craft_Config_Craft_Sound" )
		panel:TextEntry( "UI Sound", "Craft_Config_UI_Sound" )
		panel:TextEntry( "Select Sound", "Craft_Config_Select_Sound" )
		panel:TextEntry( "Fail Sound", "Craft_Config_Fail_Sound" )
		panel:TextEntry( "Drop Sound", "Craft_Config_Drop_Sound" )
		panel:TextEntry( "Destroy Sound", "Craft_Config_Destroy_Sound" )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Mining", "Mining Config", "", "", function( panel )
		panel:NumSlider( "Max Rock Health", "Craft_Config_Rock_Health", 0, 1000, 0 )
		panel:NumSlider( "Rock Respawn Time", "Craft_Config_Rock_Respawn", 1, 3600, 0 )
		panel:NumSlider( "Max Tree Health", "Craft_Config_Tree_Health", 0, 1000, 0 )
		panel:NumSlider( "Tree Respawn Time", "Craft_Config_Tree_Respawn", 1, 3600, 0 )
	end )
end )
