
hook.Add( "PopulateToolMenu", "CraftingOptions", function()
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Options", "Table Health", "", "", function( panel )
		panel:NumSlider( "Max Health", "Craft_Config_MaxHealth", 0, 1000, 0 )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Options", "Table Appearance", "", "", function( panel )
		panel:TextEntry( "Table Model", "Craft_Config_Model" )
		panel:TextEntry( "Table Material", "Craft_Config_Material" )
		panel:TextEntry( "Table Color", "Craft_Config_Color" )
	end )
	spawnmenu.AddToolMenuOption( "Options", "Crafting Table", "Craft_Options", "Table Sounds", "", "", function( panel )
		panel:TextEntry( "Item Place Sound", "Craft_Config_Place_Sound" )
		panel:TextEntry( "Craft Sound", "Craft_Config_Craft_Sound" )
	end )
end )
